---
- hosts: localhost
  connection: local
  gather_facts: true

  vars:
    osx_script: ./files/osx.sh

    mas_installed_apps:
      - { id: 1287239339, name: "ColorSlurp" }
      - { id: 571213070, name: "DaVinci Resolve" }

    homebrew_installed_packages:
      - fzf
      - jdtls
      - kotlin-language-server
      - neovim
      - rbenv # Ruby manager
      - ripgrep
      - stow

    homebrew_cask_apps:
      - angry-ip-scanner
      - daisydisk
      - dbeaver-community
      - fork
        #- google-chrome
      - handbrake # Video compression
      - latest # Keep app updated
      - monitorcontrol
      - obs
      - obsidian
      - raycast # App launcher similar to Spotlight
      - rectangle # Move windows around
      - shottr # Better screenshot tool
      - warp

    homebrew_uninstalled_packages: []

  tasks:
    - import_tasks: tasks/osx.yml
    - import_tasks: tasks/shell.yml

  roles:
    - geerlingguy.mac.homebrew
    - geerlingguy.mac.mas

